name: Review Visualizer Continious Deployment(CD)
on:
  workflow_run:
    workflows: ["Review Visualizer Continious Integration(CI)"]
    types:
      - completed
env:
  AZURE_WEBAPP_NAME: my-app    # Set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # Set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'
  OS: ubuntu-latest
jobs:
  deploy:
    strategy:
      matrix:
        project: ['Generator','WebApi']
    runs-on: ${{ matrix.os }}
    steps:
        - name: Set env variables
          run: |
            echo "AZURE_WEBAPP_PACKAGE_PATH=ReviewVisualizer.${{ matrix.project }}/publish" >> $GITHUB_ENV
            echo "AZURE_WEBAPP_NAME=${{ matrix.project }}-App" >> $GITHUB_ENV
            echo "ARTIFACT_NAME=${{ matrix.project }}-publish-artifacts" >> $GITHUB_ENV
        
        - name: Login to Azure
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
        - name: Download published project
          uses: actions/download-artifact@v4
          with:
            name: ${{ env.ARTIFACT_NAME }}

        - name: Output contents
          run: ls

        # - name: Run Azure webapp deploy action for ${{ matrix.project }}
        #   uses: azure/webapps-deploy@v3
        #   with: 
        #     app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        #     package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
        - name: Azure Logout
          run: |
            az logout