name: Prepare .NET environment
on:
  workflow_call:
    inputs:
      os:
        description: Operating system to run on
        type: string
        default: ubuntu-latest
        required: false
      project-path:
        type: string
        required: true
        description: Path to the project file relative to repository root folder
jobs:
  prepare:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Setup .NET 📦
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true

      - name: Install dependencies 📂
        env:
          PROJECT_PATH: ${{ inputs.project-path }}
        run: dotnet restore $PROJECT_PATH